[package]
name = "dxf_io"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.29", features = ["extension-module"] }
numpy = "0.29"
ndarray = "0.16"
rayon = "1.10"
hashbrown = "0.14"
smallvec = "1.13"
regex = "1.10"
rustc-hash = "2.1"

[build-dependencies]
pyo3-build-config = "0.23"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[lib]
name = "dxf_io"
crate-type = ["cdylib"]
