"""Type stubs for the compiled Rust extension ``dxf_io._dxf_io``."""

import numpy as np
import numpy.typing as npt

class RawMesh:
    """Triangle mesh produced by the Rust parser."""

    points: list[list[float]]
    faces: list[list[int]]
    labels: list[int]

    def __init__(
        self,
        points: list[list[float]],
        faces: list[list[int]],
        labels: list[int],
    ) -> None: ...
    @property
    def n_points(self) -> int: ...
    @property
    def n_faces(self) -> int: ...
    @property
    def n_components(self) -> int: ...
    def points_array(self) -> npt.NDArray[np.float64]: ...
    def faces_array(self) -> npt.NDArray[np.uint64]: ...
    def labels_array(self) -> npt.NDArray[np.uint64]: ...
    def to_dxf(self) -> str: ...

def parse_dxf_fast(dxf_content: str, decimals: int = 6) -> RawMesh: ...
def write_dxf_fast(points: list[list[float]], faces: list[list[int]]) -> str: ...
